---
- hosts: all
  tasks:
  - name: Run PS1 file to ad AD proxy for Azure
    win_file:
      path: C:\scripts
      state: directory
  
  - name: Copy script
    win_copy:
      src: /var/scripts/AzureADProxyAdd.ps1
      dest: 'C:\scripts\AzureADProxyAdd.ps1'
      remote_src: no

  - name: Run script to start AD Proxy for Azure.
    win_command: powershell.exe -ExecutionPolicy Bypass -File C:/scripts/AzureADProxyAdd.ps1
